/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    AFloatButtonGroup: typeof import('ant-design-vue/es')['FloatButtonGroup']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputGroup: typeof import('ant-design-vue/es')['InputGroup']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASegmented: typeof import('ant-design-vue/es')['Segmented']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title_bar: typeof import('./src/components/title_bar.vue')['default']
    Title_bar_history: typeof import('./src/components/title_bar_history.vue')['default']
    Title_bar_histroy: typeof import('./src/components/title_bar_histroy.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    Y_card: typeof import('./src/components/y_card.vue')['default']
    Y_float_box: typeof import('./src/components/y_float_box.vue')['default']
    Y_input: typeof import('./src/components/y_input.vue')['default']
    YInput: typeof import('./src/components/YInput.vue')['default']
  }
}
