/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AWatermark: typeof import('ant-design-vue/es')['Watermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title_bar: typeof import('./src/components/title_bar.vue')['default']
    Title_bar_history: typeof import('./src/components/title_bar_history.vue')['default']
    Title_bar_setting: typeof import('./src/components/title_bar_setting.vue')['default']
    Y_card: typeof import('./src/components/y_card.vue')['default']
    Y_input: typeof import('./src/components/y_input.vue')['default']
  }
}
